# Generated by Django 5.1.3 on 2026-03-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
