# Generated by Django 5.1.3 on 2026-03-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
