# Generated by Django 6.0.3 on 2026-03-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicerequest_stories_alter_servicerequest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service',
            field=models.CharField(choices=[('inside', 'Inside'), ('outside', 'Outside'), ('both', 'Inside & Outside')], max_length=20),
        ),
    ]
